@baseUrl = https://api.sonkim.upme.dev/bu-api
# @baseUrl = http://localhost:1337/bu-api


### Login
POST https://api.sonkim.upme.dev/auth/local HTTP/1.1
Content-Type: application/json

{
    "identifier": "cgv",
    "password": "123123"
}

### Articles
GET {{baseUrl}}/articles?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs


### Article detail
GET {{baseUrl}}/articles/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs

### Loyalty programs
GET {{baseUrl}}/loyalty-programs?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs


### Loyalty program detail
GET {{baseUrl}}/loyalty-programs/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs

### Promotions
GET {{baseUrl}}/promotions?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs


### Promotions detail
GET {{baseUrl}}/promotions/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs

### Stores
GET {{baseUrl}}/stores?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs


### Store detail
GET {{baseUrl}}/stores/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNjM2NTMxODMzLCJleHAiOjE2MzY3OTEwMzN9.MLVIzRW_0GWcvXyPVeaBXi5lAL2IadftHmejY2-puWs
