# @baseUrl = https://api.sonkim.upme.dev/bu-api
@baseUrl = http://localhost:1337/bu-api

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiYnVzIjpbMl0sImlhdCI6MTY0MDE0MjIxMSwiZXhwIjoxNjQwNDAxNDExfQ.74dqDVF2ypvlskQLT7wpEZCMVTkFOscI926QsFtxlsA
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0a3YiOm51bGwsImlhdCI6MTY0MDA4MDkzNSwiZXhwIjoxNjQ1MjY0OTM1LCJzdWIiOiI5In0.eknTMBJtmRPreX3OCZ7AMsuNafSsvoMcvgPYkENTdQg

### Login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "identifier": "cgv",
    "password": "123123"
}

### Refresh token
### Set "renew" = true if you want to re-new the refresh token
POST {{baseUrl}}/refresh HTTP/1.1
content-type: application/json

{
    "refresh_token": "{{refresh_token}}",
    "renew": true
}

### Revoke token
POST {{baseUrl}}/revoke HTTP/1.1
content-type: application/json

{
    "refresh_token": "{{refresh_token}}"
}

### Upload image (Need to use Postman to test)
POST {{baseUrl}}/uploads HTTP/1.1
Authorization: Bearer {{access_token}}

{
    "files": "Files upload max 5 file and 5M each"
}

### Get list media uploaded
GET {{baseUrl}}/uploads HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Get detail media
GET {{baseUrl}}/uploads/61 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Delete detail media
DELETE {{baseUrl}}/uploads/61 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Articles
GET {{baseUrl}}/articles?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Create articles
POST {{baseUrl}}/articles
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "title article test 1",
    "slug": "title-slug-for-article-112",
    "body": "some body 1",
    "business_unit": 2,
    "avatar": 38,
    "locale": "vi-VN"
}

### Edit articles
PUT {{baseUrl}}/articles/16
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "title article test 3",
    "slug": "title-slug-for-article-33",
    "body": "some body 3",
    "business_unit": 2,
    "avatar": 4,
    "locale": "vi-VN"
}


### Article detail
GET {{baseUrl}}/articles/7 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Loyalty programs
GET {{baseUrl}}/loyalty-programs?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Loyalty program detail
GET {{baseUrl}}/loyalty-programs/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Promotions
GET {{baseUrl}}/promotions?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Promotions detail
GET {{baseUrl}}/promotions/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Stores
GET {{baseUrl}}/stores?_start=0&_limit=10&_sort=id:DESC
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Store detail
GET {{baseUrl}}/stores/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
